### ISSUE TITLE
Is the site completely shut down? 

### ISSUE THREAD

**Issue by LatinLver21** [nktfh100/exercitia-latina#14]
Is the site down for good?

**Comment by nktfh100** [comment]
Yes, nothing I can do.
Sorry!

**Comment by LatinLver21** [comment]
Are there any sites similar to this one?

**Comment by nktfh100** [comment]
I don't think so, maybe someone else will host it

**Comment by bobmounger** [comment]
This is similar 
http://www.didascalica.it/LD.html 
but has some errors. The author will fix if you ask politely.
I really liked your version
